"""
Pydantic models for the Banking Support System API.

Defines request and response schemas used by the FastAPI endpoints.
"""

from typing import Optional

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Incoming query submitted by a customer-service representative."""

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Customer service representative's question about a banking topic.",
    )
    rep_name: Optional[str] = Field(
        default="Anonymous",
        max_length=100,
        description="Name of the representative submitting the query.",
    )


class QueryResponse(BaseModel):
    """Full pipeline result returned to the frontend after agent processing."""

    original_question: str = Field(
        description="The raw question exactly as submitted by the representative.",
    )
    reformulated_query: str = Field(
        description="Search-optimised query produced by the Reformulation Agent.",
    )
    answer: str = Field(
        description="Answer generated by the Search Agent from the knowledge base.",
    )
    source_document: str = Field(
        description="Knowledge-base document(s) used to generate the answer.",
    )
    confidence_score: int = Field(
        ge=0,
        le=100,
        description="Quality confidence score (0-100) assigned by the Validation Agent.",
    )
    validation_reasoning: str = Field(
        description="Explanation of the confidence score and quality assessment.",
    )
    improvement_needed: str = Field(
        description="Specific improvements suggested when confidence is below 80%.",
    )
    response_time_ms: int = Field(
        ge=0,
        description="Total pipeline processing time in milliseconds.",
    )
